const errorName = {
  BADREQUEST: "BADREQUEST",
  NOTFOUND: "NOTFOUND",
  INTERNALSERVER: "INTERNALSERVER",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  CONFLICT_EMAIL: "CONFLICT EMAIL",
  CONFLICT_PHONE: "CONFLICT PHONE",
  INVALIDOTP: "INVALID OTP",
  OTPEXPIRED: "OTP EXPIRED",
  ALREADYVERIFIED: "ALREADY VERIFIED",
  PASSWORD_MISMATCH: "PASSWORD MISMATCH",
  WEAKPASSWORD: "WEAK PASSWORD"
};

const successName = {
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",
  SIGNUP: "SIGNUP SUCCESSFUL_CHECK_EMAIL_FOR_OTP",
  EMAILVERIFIED: "EMAIL VERIFIED SUCCESSFULLY",
  OTPSENT: "OTP SENT SUCCESSFULLY",
  LOGIN: "LOGIN SUCCESSFUL",
  PASSWORDRESET: "PASSWORD RESET SUCCESSFULLY"
};

module.exports = {
  errorName,
  successName
};
