const errorName = {
  BADREQUEST: "BADREQUEST",
  NOTFOUND: "NOTFOUND",
  INTERNALSERVER: "INTERNALSERVER",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  CONFLICT_EMAIL: "CONFLICT_EMAIL",
  CONFLICT_PHONE: "CONFLICT_PHONE",
  INVALIDOTP: "INVALIDOTP",
  OTPEXPIRED: "OTPEXPIRED",
  ALREADYVERIFIED: "ALREADYVERIFIED",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  WEAKPASSWORD: "WEAKPASSWORD"
};

const successName = {
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",
  SIGNUP: "SIGNUP_SUCCESSFUL_CHECK_EMAIL_FOR_OTP",
  EMAILVERIFIED: "EMAIL_VERIFIED_SUCCESSFULLY",
  OTPSENT: "OTP_SENT_SUCCESSFULLY",
  LOGIN: "LOGIN_SUCCESSFUL",
  PASSWORDRESET: "PASSWORD_RESET_SUCCESSFULLY"
};

module.exports = {
  errorName,
  successName
};
